@startuml Adventure

class Game
{
    Jugar()
    -tiempoJugado
}
class Player
{
    Controlar()
    -puntaje
    -intento
}

class Objeto{
    -color
    -tamaño
}
class Key
{
    Acceder()
   
}
class Puntaje{
    Puntaje()
    updateText()
    addScore()
    draw()
}
class Lanza 
{
    Atacar()
    -daño
}

class Sala
{
    -paredes
    -tamaño
    -puertas
    -suelo
    -items
}
class Door 
{
    DejarPasar()
    -tamaño 
    -textura
}
class Laberinto
{
    -cantidadSalas
}
class Pared
{
    -textura
    -tamaño
}

class Enemy
{
    Atacar()
    Perseguir()
    -daño
   
}

class Entidad{
    -tamaño
    -textura
    -vida
    -velocidad

}

Game *-- "1" Player

Key -|> Objeto
Lanza -|> Objeto

Player "1" o-- "1" Objeto

Game "1" *-- "1"Laberinto
Game "1" *-- "1" Puntaje
Laberinto "1" *-- "*"Sala
Player "1" o--"1"Sala
Sala "1" *-- "1" Door 
Sala "1" *-- "*" Pared

Player -|> Entidad
Enemy -|> Entidad

@enduml