@startuml Adventure

class Game
{
    Game()
    ~Game()
    run()
    handleStartScreenEvents()
    handleGameEvents()
    transitioningMusic()
    update()
    render()
    resetGame()
    gameOver()
    gameCompleted()
    handleGameCompleted()
    -Puntaje
    -GameObject
    -Laberinto
    -Player
    -Enemy
    -Door
    -Key

}
class Enemy
{
    -x
    -y
    -speed
    -alive
    -Filas
    -Columnas
    -laberinto[][]
    Enemy()
    esMovimientoValido()
    updateAnimation()
    updateMovement()
    checkRespawn()
    kill()
   
}
class Player
{
    -x
    -y
    -moveSpeed
    -hasSword
    -hasKey
    -Filas
    -Columnas
    -laberinto[][]
    Player()
    moverPersonaje()
    esMovimientoValido()
    update()
}
class Puntaje
{
    -cantidadVidas
    -score
    Puntaje()
    updateText()
    addScore()
    draw()
    restarVidas()
}
class GameObject
{
    GameObject()
    setPosition()
    getPosition()
}

class Key
{
    Key()
    respawn()
   
}
class Sword
{
    Atacar()
    -danio
    -collected
    -texture
    -sprite
    -position
    Sword()
    ~Sword()
    isCollected()
    collect()
    drop()
    updatePosition()
    getDistanceTo()
    move()
}

class Door 
{
    -simbolo
    -sprite
    Door()
}

class Sala
{
    generarSala()
}

class Laberinto
{
    mapa1
    texturaBloques
    generarBloque()
    Laberinto()
    ~Laberinto()
    checkCollision()
}


Key -|> GameObject
Sword -|> GameObject

Player "1" o-- "1,2" GameObject

Game "1" *-- "1" Player
Game "1" *-- "1"Laberinto
Game "1" *-- "1"Enemy
Game "1" *-- "1" Puntaje
Sala "1" *-- "1"Laberinto
Player "1" o--"1"Sala
Sala "1" *-- "1" Door 

@enduml